# Change these first
owner: oparacriacoes # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ajor
    url: https://www.ajor.org.br
  - name: Ponte
    url: https://ponte.org
  - name: Sumauma
    url: https://sumauma.com
  - name: Agenda Preta
    url: https://agendapreta.com
  - name: O Joio e o Trigo
    url: https://ojoioeotrigo.com.br/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Opará Status Page
  introTitle: "**Veja Aqui** o status dos sites."
  introMessage: Entre em contato para qualquer dúvida
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Site
      href: https://opara.me

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
